# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: CodingBobby
author: Bob Walter
email: bob.walter@outlook.de
description: >-
  Personal blog of Bob Walter, talking about what interests him and what he learned today.
  He is also showing his projects and lists useful resources for developers
  and science students.
baseurl: ""
url: "https://codingbobby.xyz"
twitter_username: BobbyCoding
github_username: CodingBobby

# Build settings
theme: no-style-please
plugins:
  - jekyll-feed
  - jekyll-seo-tag

sass:
  style: compressed

theme_config:
  back_home_text: ".."
  date_format: "%Y-%m-%d"
  show_description: false

goat_counter: "codingbobby"
permalink: /:slug.html

favicon: "./favicon.png"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
